---
sidebar: sidebar 
permalink: ONTAP/choose-ontap-910-later.html 
keywords: choose ontap target version, ontap update recommendations, identify ontap target version 
summary: ONTAPストレージシステムをアップグレードする前に、ONTAPの各バージョンのメリットとリスクを理解してください。 
---
= ONTAPターゲットのバージョン9.10以降を選択
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムのONTAPバージョンを選択する前に、メリットを特定し、ONTAPターゲットバージョンに関連するリスクを理解しておくことが非常に重要です。

ターゲットバージョンを選択して現在のバージョンと比較すると、ONTAPの特定のバージョンに更新するメリットを確認できます。また、ONTAPの特定のバージョンへの更新時に解決されるリスクと新しいリスク（存在する場合）を確認することもできます。


NOTE: この機能は、ONTAP 9.10以降のバージョンを実行している場合にのみ使用できます。

.手順
. BlueXP  の左側のナビゲーションで、*[ヘルス]>[ソフトウェアアップデート]*を選択します。
+
ソフトウェアの更新が必要なクラスタのリストが表示されます。推奨されるターゲットバージョンに更新するか、別のバージョンを選択できます。



|===
| 状況 | 操作 


 a| 
推奨バージョンに更新
 a| 
. [ターゲットバージョン]列で*[バージョンの比較]*をクリックして、推奨されるONTAPバージョンに更新することによる機能の利点とリスクの利点を表示します。
. 解決されるリスク、残るリスク、更新後に導入される新しいリスクに関する情報を選択して表示します。
. 必要に応じて、*[アップデートプランのダウンロード]*をクリックして、アップデートプランのコピーをダウンロードします。
. [更新の開始]*をクリックして、更新プロセスを開始します。




 a| 
別のバージョンを選択したい
 a| 
. [ターゲットバージョン]列で、ドロップダウンをクリックして*[他のバージョンの選択]*を選択します。
. バージョンを選択すると、機能のメリットとリスクのメリットが表示されます。
. 解決されるリスク、残るリスク、更新後に導入される新しいリスクに関する情報を選択して表示します。
. 必要に応じて、*[アップデートプランのダウンロード]*をクリックして、アップデートプランのコピーをダウンロードします。
. [更新の開始]*をクリックして、更新プロセスを開始します。


|===