---
sidebar: sidebar 
permalink: ONTAP/fix-blockers-warnings.html 
keywords: fix ontap blockers and warnings, ontap update precheck, acknowledge warnings 
summary: ONTAPブロッカーを修正し、ONTAPの更新を完了できない警告を承認します。 
---
= ONTAPブロッカーの修正と承認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPストレージシステムのONTAPターゲットバージョンを特定したら、ONTAPストレージシステムを更新する前に、すべてのブロッカーを修正して承認し、警告を確認する必要があります。

すべてのブロッカーを修正して承認することは必須であり、シームレスなソフトウェア更新プロセスを保証します。

.手順
. BlueXP  の左側のナビゲーションで、*[ヘルス]>[ソフトウェアアップデート]*を選択します。
+
ソフトウェアの更新が必要なクラスタのリストが表示されます。

. ストレージシステムのONTAPターゲットのバージョンを確認します。ONTAPターゲットバージョンの識別については、を参照してください link:../ONTAP/choose-ontap-910-later.html["ONTAPターゲットのバージョン9.10以降を選択"]。
. ONTAPのターゲットバージョンを決定したら、*[更新の準備]*をクリックして更新プロセスを開始します。
+
ブロッカーと警告のリストが表示されます。

. ブロッカーを選択して、ブロッカーを修正する手順を表示します。
. ブロッカーを修正するために、提供された手順を手動で実行します。
. 修正されたブロッカーを選択し、*[選択内容を確認]*をクリックして、ブロッカーが修正されたことを確認します。



NOTE: 更新を続行するには、すべてのブロックを修正して承認する必要があります。

. ソフトウェアの更新を進める前に、*警告*タブをクリックして警告を確認してください。
. [確認]*タブをクリックして、修正されたブロッカーを表示します。
. [更新を続行する]*をクリックして、更新プロセスを続行します。

