---
sidebar: sidebar 
permalink: get-started/software-updates-faq.html 
keywords: ontap update faq, ontap update frequently asked questions, software updates faq, software updates frequently asked questions, troubleshooting 
summary: BlueXP  ソフトウェアの更新に関するよくある質問とその回答をご覧ください。 
---
= BlueXP  ソフトウェアの更新に関するよくある質問
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BlueXP  ソフトウェアの更新について詳しく知りたい場合や、トラブルシューティングについてサポートが必要な場合は、これらの質問を確認して回答を得ることができます。

* BlueXP  ソフトウェア・アップデートのURLは何ですか？*

BlueXP  コンソールにアクセスするには、ブラウザで次のように入力します。 https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^]

* BlueXP  ソフトウェアアップデートを使用するにはライセンスが必要ですか？*

ネットアップライセンスファイル（NLF）は必要ありません。

*クラスタのONTAPバージョンを更新しても、[履歴]タブにクラスタが表示されないのはなぜですか。*

[History]タブにクラスタが表示されるまでに2~3時間かかります。クラスタのONTAPバージョンが更新されると、AutoSupportが生成されます。AutoSupportデータが処理され、最新バージョンのONTAPが反映されるまでに2~3時間かかります。

*クラスタのONTAPバージョンを更新しても、ソフトウェア更新ダッシュボードに古いバージョンのONTAPが表示されるのはなぜですか。*

[History]タブにクラスタが表示されるまでに2~3時間かかります。クラスタのONTAPバージョンが更新されると、AutoSupportが生成されます。AutoSupportデータが処理され、最新バージョンのONTAPが反映されるまでに2~3時間かかります。

*アップデートごとに異なる画面が表示されるのはなぜですか？*

これは、現在のONTAPバージョンとクラスタ用のBlueXP  Connectorを使用できないためです。BlueXP  ConnectorはBlueXP  内でONTAPの更新を実行するため、更新のためにBlueXP  から移動する必要はありません。BlueXP  Connectorがない場合はSystem Managerにリダイレクトされ、ONTAPクラスタのクレデンシャルを再入力する必要があります。ONTAPのバージョンごとのONTAP更新プロセスの詳細については、を参照してください link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["サポート対象の ONTAP システム"]。

*クラスタを検出するには何が必要ですか？*

目的のクラスタでONTAPの更新を実行するには、クラスタに接続するためのONTAPクラスタIPとadminクレデンシャルが必要です。クラスタ検出の一環として、ONTAPの更新が自動的に実行されるように、これらの詳細を指定する必要があります。
