---
sidebar: sidebar 
permalink: get-started/software-updates.html 
keywords: ontap 9.10, ontap update, supported systems for ontap update, ontap version, software updates benefits 
summary: BlueXP  ソフトウェアアップデートを使用して、ONTAPストレージシステムをシームレスに更新し、新機能や強化された機能を利用できます。 
---
= BlueXP  ソフトウェアアップデートの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BlueXP  ソフトウェア更新サービスを使用すると、お客様がONTAPの更新を合理化できます。これは、コストの削減、重要なワークロードの高速化、セキュリティの向上に役立ちます。

BlueXP  ソフトウェア更新サービスは、評価、計画、実行のプロセスを自動化します。Intelligent Upgrade Advisorは、特定の環境に最適なバージョンを予測し、問題の修正、効率の向上、システムセキュリティの向上を目的としたバージョンを推奨します。これにより、お客様はニーズに最適なオプションを判断できます。その後、ソフトウェアパッケージが配布され、サポートサービスとは関係なく、自動非配布アップグレード（ANDU）が自動的に実行されます。



== サポートされるシステム



=== ONTAPシステム

BlueXP  ソフトウェア更新サービスを使用してONTAPの更新を完了できるのは、ONTAP 9.10以降のバージョンを実行している場合のみです。

次の情報は、ONTAPのバージョンごとのソフトウェア更新プロセスを示しています。

|===
| * 現在の ONTAP バージョン * | *更新プロセス* 


| 9.12以上 | ONTAPアップデートのすべての手順は、BlueXP  内で実行されます。 


| 9.10～9.12 | ONTAPアップデートの準備は、BlueXP  ソフトウェアアップデート画面で行います。ONTAPの実際の更新を実行するには、System Managerに移動します。BlueXP  内でONTAP更新のすべての手順を実行するには、を実行する必要があり link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["コネクタの設定"]ます。 


| 9.8～9.10 | ONTAPアップデートの準備は、BlueXP  ソフトウェアアップデート画面で行います。ONTAPの実際の更新を実行するには、System Managerに移動します。 


| 9.7未満 | このクラスタでは、ONTAPの自動更新はサポートされていません。ONTAPを手動で更新する必要があります。詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ストレージシステムを手動で更新する"]。 
|===


== BlueXP  ソフトウェアアップデートを使用するメリット

ONTAPストレージシステムを更新すると、ストレージシステムのパフォーマンス、セキュリティ、機能性を向上させることができます。

ONTAPストレージシステムを更新するメリットには、次のようなものがあります。

* 新しいプロトコル、データサービス、クラウド統合オプションなど、ONTAPが提供する最新の機能や拡張機能を利用できます。
* システムの安定性、信頼性、またはセキュリティに影響する可能性のあるバグや脆弱性を修正できます。
* 最新のパッチと改善点を適用することで、システムのパフォーマンスと効率を最適化できます。
* 他のNetApp製品、サードパーティアプリケーション、クラウドプロバイダとの互換性と相互運用性を確保できます。
* NetAppでは、最新バージョンのONTAP OSに対して継続的なサポートとメンテナンスを提供しています。




== コスト

ネットアップは、このサービスの利用に対して料金を請求することはありません。
